SELECT 
    SEAT_PLAN.CLASS, 
    SEAT_PLAN.SEAT,
    SEAT_PLAN.PLANE_ROW, 
FROM 
    (SELECT *, 'Yes' AS FLOW_CARD
    FROM PD2024_WK04_FLOW_CARD
    
    UNION ALL
    
    SELECT *, 'No' AS FLOW_CARD
    FROM PD2024_WK04_NON_FLOW_CARD
    
    UNION ALL
    
    SELECT *, 'No' AS FLOW_CARD
    FROM PD2024_WK04_NON_FLOW_CARD2) AS PASSENGER_INFO

FULL OUTER JOIN PD2024_WK04_SEAT_PLAN AS SEAT_PLAN
ON 
    PASSENGER_INFO.CLASS = SEAT_PLAN.CLASS 
    AND PASSENGER_INFO.PLANE_ROW = SEAT_PLAN.PLANE_ROW
    AND PASSENGER_INFO.SEAT = SEAT_PLAN.SEAT
WHERE FLOW_CARD IS NULL
GROUP BY SEAT_PLAN.CLASS, SEAT_PLAN.PLANE_ROW, SEAT_PLAN.SEAT, FLOW_CARD;