SELECT 
    DATE(SPLIT_PART(FLIGHT_DETAILS,'//',1)) AS "DATE",
    SPLIT_PART(FLIGHT_DETAILS,'//',2) AS FLIGHT_NUMBER,
    SPLIT_PART(SPLIT_PART(FLIGHT_DETAILS, '//', 3), '-', 1) AS "FROM",
    SPLIT_PART(SPLIT_PART(FLIGHT_DETAILS, '//', 3), '-', 2) AS "TO",
    SPLIT_PART(FLIGHT_DETAILS,'//',4) AS CLASS,
    ROUND(SPLIT_PART(FLIGHT_DETAILS,'//',5),1) AS PRICE,
    IFF(FLOW_CARD = '1', 'Yes','No') AS FLOW_CARD,
    BAGS_CHECKED,
    MEAL_TYPE
FROM PD2024_WK01;