CREATE OR REPLACE TEMP TABLE UNIONED AS
(
SELECT 
    CASE
        WHEN CLASS = 'Economy' THEN 'First Class'
        WHEN CLASS = 'First Class' THEN 'Economy'
        WHEN CLASS = 'Business Class' THEN 'Premium Economy'
        WHEN CLASS = 'Premium Economy' THEN 'Business Class'
    END AS CLASS,
    IFF(FLOW_CARD = '1', 'Yes','No') AS FLOW_CARD,
    QUARTER(TO_DATE("DATE", 'DD/MM/YYYY')) AS "QUARTER",
    PRICE
FROM PD2024_WK02_FLOW_CARD

UNION

SELECT 
    CASE
        WHEN CLASS = 'Economy' THEN 'First Class'
        WHEN CLASS = 'First Class' THEN 'Economy'
        WHEN CLASS = 'Business Class' THEN 'Premium Economy'
        WHEN CLASS = 'Premium Economy' THEN 'Business Class'
    END AS CLASS,
    IFF(FLOW_CARD = '1', 'Yes','No') AS FLOW_CARD,
    QUARTER(TO_DATE("DATE", 'DD/MM/YYYY')) AS "QUARTER",
    PRICE
FROM PD2024_WK02_NON_FLOW_CARD
);

(SELECT  *
FROM UNIONED
PIVOT(MEDIAN(PRICE) FOR CLASS IN (ANY ORDER BY CLASS))
ORDER BY FLOW_CARD, QUARTER)

UNION ALL

(SELECT *
FROM UNIONED
PIVOT(MIN(PRICE) FOR CLASS IN (ANY ORDER BY CLASS))
ORDER BY FLOW_CARD, QUARTER)

UNION ALL

(SELECT *
FROM UNIONED
PIVOT(MAX(PRICE) FOR CLASS IN (ANY ORDER BY CLASS))
ORDER BY FLOW_CARD, QUARTER);