SELECT 
    FLIGHTS.DATE,
    FLIGHT_FROM,
    FLIGHT_TO,
    FLIGHTS.FLIGHT_NUMBER,
    CUSTOMERS.CUSTOMER_ID,
    LAST_DATE_FLOWN,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    GENDER,
    TICKET_PRICE
    
FROM PD2024_WK05_PREP_AIR_CUSTOMERS AS CUSTOMERS

INNER JOIN PD2024_WK05_PREP_AIR_TICKET_SALES AS SALES
ON CUSTOMERS.CUSTOMER_ID = SALES.CUSTOMER_ID

INNER JOIN PD2024_WK05_PREP_AIR_2024_FLIGHTS AS FLIGHTS
ON 
    FLIGHTS.FLIGHT_NUMBER = SALES.FLIGHT_NUMBER
    AND FLIGHTS.DATE = SALES.DATE;


SELECT 
    DATE('2024-01-31') AS FLIGHT_UNBOOKED_AS_OF,
    FLIGHTS.DATE,
    FLIGHTS.FLIGHT_NUMBER,
    FLIGHT_FROM,
    FLIGHT_TO
FROM PD2024_WK05_PREP_AIR_2024_FLIGHTS AS FLIGHTS

LEFT JOIN PD2024_WK05_PREP_AIR_TICKET_SALES AS SALES
ON FLIGHTS.DATE = SALES.DATE AND FLIGHTS.FLIGHT_NUMBER = SALES.FLIGHT_NUMBER
WHERE SALES.DATE IS NULL;


SELECT 
    CUSTOMERS.CUSTOMER_ID,
    (CASE
        WHEN DATEDIFF(MONTH, DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) <=3 THEN 'Recent fliers'
        WHEN DATEDIFF(MONTH, DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) >3 AND DATEDIFF(MONTH,        DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) <=6 THEN 'Taking a break'
        WHEN DATEDIFF(MONTH, DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) >6 AND DATEDIFF(MONTH,        DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) <=9 THEN 'Been away a while'
        WHEN DATEDIFF(MONTH, DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) >9 THEN 'Lapsed Customers'
    END) AS CUSTOMER_CATEGORY,
    DATEDIFF(day, DATE(LAST_DATE_FLOWN, 'DD/MM/YYYY'), DATE('2024-01-31')) AS DAYS_SINCE_LAST_FLOWN,
    LAST_DATE_FLOWN,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    GENDER
FROM PD2024_WK05_PREP_AIR_CUSTOMERS AS CUSTOMERS

LEFT JOIN PD2024_WK05_PREP_AIR_TICKET_SALES AS SALES
ON CUSTOMERS.CUSTOMER_ID = SALES.CUSTOMER_ID

LEFT JOIN PD2024_WK05_PREP_AIR_2024_FLIGHTS AS FLIGHTS
ON FLIGHTS.DATE = SALES.DATE AND FLIGHTS.FLIGHT_NUMBER = SALES.FLIGHT_NUMBER
WHERE FLIGHTS.DATE IS NULL;