CREATE OR REPLACE TEMP TABLE UNIONED AS
(
SELECT 
    *, EXTRACT (QUARTER FROM "Date") AS QUARTER,
    'Birmingham' AS STORE
FROM PD2021_WK03_BIRMINGHAM
UNION ALL
SELECT 
    *, EXTRACT (QUARTER FROM "Date") AS QUARTER,
    'Leeds' AS STORE
FROM PD2021_WK03_LEEDS
UNION ALL
SELECT 
    *, EXTRACT (QUARTER FROM "Date") AS QUARTER,
    'London' AS STORE
FROM PD2021_WK03_LONDON
UNION ALL
SELECT 
    *, EXTRACT (QUARTER FROM "Date") AS QUARTER,
    'Manchester' AS STORE
FROM PD2021_WK03_MANCHESTER
UNION ALL
SELECT 
    *, EXTRACT (QUARTER FROM "Date") AS QUARTER,
    'York' AS STORE
FROM PD2021_WK03_YORK
);

SELECT
   SPLIT (ATTRIBUTE,'_-_')[1] AS PRODUCT,
   QUARTER,
   SUM(VALUE) AS PRODUCTS_SOLD
FROM UNIONED
UNPIVOT(VALUE FOR ATTRIBUTE IN ("New_-_Saddles", "New_-_Mudguards", "New_-_Wheels", "New_-_Bags","Existing_-_Saddles", "Existing_-_Mudguards", "Existing_-_Wheels", "Existing_-_Bags")
)
GROUP BY QUARTER,PRODUCT;

SELECT
   STORE,
   SPLIT (ATTRIBUTE,'_-_')[0] AS CUSTOMER_TYPE,
   SPLIT (ATTRIBUTE,'_-_')[1] AS PRODUCT,
   SUM(VALUE) AS PRODUCTS_SOLD
FROM UNIONED
UNPIVOT(VALUE FOR ATTRIBUTE IN ("New_-_Saddles", "New_-_Mudguards", "New_-_Wheels", "New_-_Bags","Existing_-_Saddles", "Existing_-_Mudguards", "Existing_-_Wheels", "Existing_-_Bags")
)
GROUP BY STORE, CUSTOMER_TYPE, PRODUCT;
