CREATE OR REPLACE TEMP TABLE UNIONED AS 
(
SELECT *, 'West' AS LOCATION
FROM PD2022_WK30_TOP_3_SALES_PEOPLE_PER_STORE_WEST
UNION
SELECT *, 'East' AS LOCATION
FROM PD2022_WK30_TOP_3_SALES_PEOPLE_PER_STORE_EAST
);

SELECT 
    LOCATION,
    PD2022_WK30_STORE_LOOKUP.STORE_NAME, 
    SUM(SALE_VALUE) AS STORE_SALE_VALUE,
    SALES_PERSON,
    MAX(PERCENT_OF_STORE_SALES) AS PERCENT_OF_STORE_SALES,
    (MAX(PERCENT_OF_STORE_SALES) / 100) * STORE_SALE_VALUE AS SALES_PER_PERSON,
FROM UNIONED
LEFT JOIN PD2022_WK30_STORE_LOOKUP
ON PD2022_WK30_STORE_LOOKUP.STORE_ID = UNIONED.STORE AND PD2022_WK30_STORE_LOOKUP.REGION = UNIONED.LOCATION
LEFT JOIN PD2022_WK27_INPUT
ON PD2022_WK30_STORE_LOOKUP.STORE_NAME = PD2022_WK27_INPUT.STORE_NAME AND UNIONED.LOCATION = PD2022_WK27_INPUT.REGION
GROUP BY UNIONED.LOCATION, PD2022_WK30_STORE_LOOKUP.STORE_NAME, SALES_PERSON;