-- Solution Table 1

SELECT  
    REGEXP_REPLACE(MODEL,'[^A-Z]','') AS BRAND,
    BIKE_TYPE,
    SUM(QUANTITY) AS QUANTITY_SOLD,
    SUM(VALUE_PER_BIKE*QUANTITY) AS ORDER_VALUE,
    ROUND((ORDER_VALUE / QUANTITY_SOLD), 1) AS AVG_BIKE_VALUE_SOLD_PER_BRAND_TYPE
FROM PD2021_WK02_BIKE_SALES
GROUP BY BRAND, BIKE_TYPE;

-- Solution Table 2

SELECT 
    REGEXP_REPLACE(MODEL,'[^A-Z]','') AS BRAND,
    STORE,
    SUM(VALUE_PER_BIKE*QUANTITY) AS TOTAL_ORDER_VALUE,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(AVG(DATEDIFF('day',TO_DATE(ORDER_DATE,'DD/MM/YYYY'),TO_DATE(SHIPPING_DATE,'DD/MM/YYYY'))), 1) AS AVERAGE_DAYS_TO_SHIP
FROM PD2021_WK02_BIKE_SALES
GROUP BY BRAND, STORE;