SELECT 
    EXTRACT (QUARTER FROM DATE) AS QUARTER,
    SPLIT (STORE_BIKE,' - ')[0] AS STORE,
    CASE
     WHEN LEFT(SPLIT (STORE_BIKE,' - ')[1],1) = 'M' THEN 'Mountain'
     WHEN LEFT(SPLIT (STORE_BIKE,' - ')[1],1) = 'R' THEN 'Road'
     WHEN LEFT(SPLIT (STORE_BIKE,' - ')[1],1) = 'G' THEN 'Gravel'
    ELSE SPLIT (STORE_BIKE,' - ')[1] END AS BIKE,
    ORDER_ID,
    CUSTOMER_AGE,
    BIKE_VALUE,
    EXISTING_CUSTOMER,
    EXTRACT (DAY FROM DATE) AS DAY_OF_MONTH
FROM PD2021_WK01
WHERE ORDER_ID>10;