SELECT 
   SUM( CASE WHEN VALUE > 75 THEN 1 ELSE 0 END) AS PASSED_SUBJECTS,
    ROUND(AVG(VALUE),1) AS STUDENT_AVG_SCORE,
    "Student ID" AS STUDENT_ID,
    MAX("gender") AS GENDER
FROM PD2022_WK03
UNPIVOT (VALUE FOR ATTRIBUTE IN ("Maths", "English", "Spanish", "Science", "Art", "History", "Geography"))
JOIN PD2022_WK01
ON PD2022_WK01."id" = PD2022_WK03."Student ID"
GROUP BY STUDENT_ID;